version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/data
    environment:
      - SQLITE_PATH=/app/data/kalina_news.db
      - SQLALCHEMY_DATABASE_URI=sqlite:////app/data/kalina_news.db
      - REDIS_HOST=redis
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  sqlite_data:
  redis_data:
