"""Add created_at and updated_at to Category model

Revision ID: 68414a4e4268
Revises: 
Create Date: 2025-03-19 12:27:28.552821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68414a4e4268'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('articles', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.alter_column('articles', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('articles', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ### 